#!/usr/bin/env node
// 同步 skill 指针：.codex/skills/<name>/SKILL.md 是唯一正本（随仓库分发），
// 本脚本为每个正本生成 .claude/skills/<name>/SKILL.md 指针文件（.claude/ 被 gitignore，属本地物料）。
// 触发：pnpm install（postinstall）或手动 pnpm skills:sync。新增/修改 skill 只改正本，重跑本脚本即可。
import { readdirSync, readFileSync, rmSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SOURCE = join(ROOT, ".codex", "skills");
const TARGET = join(ROOT, ".claude", "skills");
const MARKER = "<!-- generated by scripts/sync-skills.mjs -->";

// 正本 frontmatter 只取 name / description 两行原样搬运（触发词就在 description 里，两边保持一致）
function readFrontmatter(text) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (!match) throw new Error("正本缺少 frontmatter");
  const name = /^name:\s*(.+)$/m.exec(match[1])?.[1]?.trim();
  const description = /^description:\s*(.+)$/m.exec(match[1])?.[1]?.trim();
  if (!name || !description) throw new Error("正本 frontmatter 缺少 name 或 description");
  return { name, description };
}

function pointer(name, description) {
  return [
    "---",
    `name: ${name}`,
    `description: ${description}`,
    "---",
    "",
    MARKER,
    "",
    `# ${name}（指针）`,
    "",
    `本 skill 的正本在 \`.codex/skills/${name}/SKILL.md\`（随仓库分发、单一事实来源，\`.claude/\` 被 gitignore）。你应该立即用 Read 工具完整读取该文件，并严格遵循其全部 Instructions 执行；不要只凭本指针行动。`,
    "",
    "修改本 skill 时只改正本，然后运行 `pnpm skills:sync`；本文件由脚本生成，勿手改。",
    "",
  ].join("\n");
}

const canonical = existsSync(SOURCE)
  ? readdirSync(SOURCE, { withFileTypes: true }).filter((entry) => entry.isDirectory())
  : [];
mkdirSync(TARGET, { recursive: true });

let created = 0;
for (const dir of canonical) {
  const sourcePath = join(SOURCE, dir.name, "SKILL.md");
  if (!existsSync(sourcePath)) continue;
  const { name, description } = readFrontmatter(readFileSync(sourcePath, "utf8"));
  if (name !== dir.name) throw new Error(`正本目录名 ${dir.name} 与 frontmatter name ${name} 不一致`);
  mkdirSync(join(TARGET, dir.name), { recursive: true });
  writeFileSync(join(TARGET, dir.name, "SKILL.md"), pointer(name, description));
  created += 1;
}

// 清理孤儿：脚本生成的指针若正本已删除则移除；无生成标记的目录视为个人本地 skill，不动
let removed = 0;
for (const dir of readdirSync(TARGET, { withFileTypes: true })) {
  if (!dir.isDirectory()) continue;
  const pointerPath = join(TARGET, dir.name, "SKILL.md");
  if (!existsSync(pointerPath)) continue;
  const text = readFileSync(pointerPath, "utf8");
  if (!text.includes(MARKER)) continue;
  if (!canonical.some((entry) => entry.name === dir.name)) {
    rmSync(join(TARGET, dir.name), { recursive: true });
    removed += 1;
  }
}

console.log(`skills 同步完成：${created} 个指针${removed ? `，清理 ${removed} 个孤儿` : ""}`);
